uint8 this_rfid #当前rfid
uint8 target_rfid #目标rfid
---
uint32 target_rfid #目标rfid
int32 velocity_limt #速度限制
int32 angle_limt #角度限制
uint8 magnetic_state #当前磁线
string road_points #路点
uint32 weight #权重
uint32 left_magnetic_close #左边关闭传感器数量
uint32 right_magnetic_close #右边关闭传感器数量
float32  timestamp  # 时间戳
